### ISSUE TITLE
Had to change some parts to make it work

### ISSUE THREAD

**Issue by pimseb** [marcelrebmann/ngrok-domain-publisher#1]
Hi,
I'm not a coder at all and it was quite difficult for me to make the script work on my raspberry pi. I think ngroc changed the way they write the log file.
So I had to change the grep line in ngrok-domain-publish.ts
``exec(`cat ${LOG_DIR} | grep -Po 'opts=\"&{Hostname:.+?.ngrok.io'`, (error: Error, stdout: string) => {``
into
``exec(`cat ${LOG_DIR} |  grep -Po '(?<=url=http://).*(?=$)' | tail -2`, (error, stdout) => {``

my ngrok.yml looks like this :
```
authtoken: 1xxxxxxxxxxxxxxxxxxxxxxxxxT_7yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
region: eu
log_level: info
log: /home/pi/ngrok.log
tunnels:
  domoticz:
    proto: http
    addr: 192.168.1.20:8090
  4g:
    proto: http
    addr: 192.168.3.254
```
and my exec script 
```[Unit]
Description=Ngrok Domain
Reqiures=coffeestock.service


[Timer]
OnBootSec=60

[Service]
Type=simple
ExecStart=/home/pi/ngrok start domoticz
ExecStartPost=/usr/bin/node /home/pi/ngrok-domain-publisher/dist/ngrok-domain-publish.js -p telegram
Restart=on-failure
User=pi

[Install]
WantedBy=multi-user.target
```

I still have 2 problems :
- I run 2 tunnels but only get 1 on telegram and don't know how to change the script to receive the url of both tunnels
- After reboot the notification doesnt go out. I need to add a timer between Exectstart and Exectrartpost but didn't find how to do it
